# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l7vFWboKEgcK6vtvyLITQuSxPbxzS7aB

EXP 0: Introduction to python
"""

# Yashasavi Jain
# PRN: 25070123127
print("Yash")

print (2)

print ([1,2,5])

x=2
y=[1,2,5]
z=("Yash")
print(x,y,z,sep="\n")